SOURCES := $(shell find .. -name "*.java")
release:
	javac -d build $(SOURCES) #liste des sources

run:
	java -cp build Menu #nom de la classe principale

run_jar:
	java -jar puissance.jar #nom du fichier .jar
